# Generated by Django 4.2 on 2023-04-10 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('army_builder', '0002_army'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='army',
            options={'verbose_name_plural': 'Armies'},
        ),
    ]
