# Generated by Django 4.2 on 2023-04-10 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('army_builder', '0003_alter_army_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('move', models.CharField(max_length=3)),
                ('weapon_skill', models.CharField(max_length=3)),
                ('ballistics_skill', models.CharField(max_length=3)),
                ('strength', models.CharField(max_length=3)),
                ('toughness', models.CharField(max_length=3)),
                ('wounds', models.CharField(max_length=3)),
                ('attacks', models.CharField(max_length=3)),
                ('leadership', models.CharField(max_length=3)),
                ('armour_save', models.CharField(max_length=3)),
                ('max_units', models.CharField(max_length=3)),
                ('keywords', models.TextField()),
                ('points_cost', models.SmallIntegerField(default=0)),
                ('army', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='army_builder.army')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
