# Generated by Django 4.2 on 2023-04-10 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('army_builder', '0004_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='unit',
            name='specialisms',
            field=models.ManyToManyField(to='army_builder.specialism'),
        ),
    ]
