# Generated by Django 4.2 on 2023-04-10 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('army_builder', '0005_specialism_unit_specialisms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wargear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('range', models.CharField(max_length=4)),
                ('type', models.CharField(max_length=50)),
                ('strength', models.CharField(max_length=3)),
                ('armor_penetration', models.CharField(max_length=3)),
                ('damage', models.CharField(max_length=5)),
                ('points_cost', models.SmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Wargear',
            },
        ),
        migrations.AddField(
            model_name='unit',
            name='wargear',
            field=models.ManyToManyField(to='army_builder.wargear'),
        ),
    ]
