# Generated by Django 4.2 on 2023-04-10 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('army_builder', '0006_wargear_unit_wargear'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('rule', models.TextField()),
                ('specialism', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='army_builder.specialism')),
                ('wargear', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='army_builder.wargear')),
            ],
            options={
                'verbose_name_plural': 'Abilities',
            },
        ),
        migrations.AddField(
            model_name='unit',
            name='abilities',
            field=models.ManyToManyField(to='army_builder.ability'),
        ),
    ]
