# Generated by Django 4.2 on 2023-04-11 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('army_builder', '0007_ability_unit_abilities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ability',
            name='specialism',
        ),
        migrations.RemoveField(
            model_name='ability',
            name='wargear',
        ),
        migrations.AddField(
            model_name='specialism',
            name='abilities',
            field=models.ManyToManyField(to='army_builder.ability'),
        ),
        migrations.AddField(
            model_name='wargear',
            name='ability',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='army_builder.ability'),
        ),
    ]
