# Generated by Django 4.2 on 2023-04-12 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('army_builder', '0009_keyword_remove_unit_keywords_alter_wargear_ability_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wargear',
            name='armor_penetration',
        ),
        migrations.RemoveField(
            model_name='wargear',
            name='damage',
        ),
        migrations.RemoveField(
            model_name='wargear',
            name='range',
        ),
        migrations.RemoveField(
            model_name='wargear',
            name='strength',
        ),
        migrations.RemoveField(
            model_name='wargear',
            name='type',
        ),
        migrations.CreateModel(
            name='WeaponProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('range', models.CharField(max_length=4)),
                ('type', models.CharField(max_length=50)),
                ('strength', models.CharField(max_length=3)),
                ('armor_penetration', models.CharField(max_length=3)),
                ('damage', models.CharField(max_length=5)),
                ('ability', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='army_builder.ability')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='wargear',
            name='weapon_profiles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='army_builder.weaponprofile'),
        ),
    ]
