# Generated by Django 4.2 on 2023-04-13 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('army_builder', '0010_remove_wargear_armor_penetration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('no_to_select', models.SmallIntegerField(default=-1)),
                ('abilities', models.ManyToManyField(blank=True, to='army_builder.ability')),
                ('nested_options', models.ManyToManyField(blank=True, to='army_builder.option')),
                ('wargear', models.ManyToManyField(blank=True, to='army_builder.wargear')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
