# Generated by Django 4.2 on 2023-04-13 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('army_builder', '0011_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wargear',
            name='weapon_profiles',
        ),
        migrations.AddField(
            model_name='wargear',
            name='weapon_profiles',
            field=models.ManyToManyField(blank=True, to='army_builder.weaponprofile'),
        ),
    ]
